#!/bin/sh

# Mimeapp script for adding torrent to transmission-daemon, but will also start the daemon first if not running.

# transmission-daemon sometimes fails to take remote requests in its first moments, hence the sleep.

pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon..." && sleep 3)

transmission-remote -a "$@" && notify-send "Torrent added." --icon "/home/anass/github/dotfiles/scripts/torrent_icon.png"
