#!/usr/bin/env bash
#TR_APP_VERSION
#TR_TIME_LOCALTIME
#TR_TORRENT_DIR
#TR_TORRENT_HASH
#TR_TORRENT_ID
#TR_TORRENT_NAME



notify-send "Transmission finished downloading $TR_TORRENT_NAME" --icon "/home/anass/github/dotfiles/scripts/done_icon.png"

